### ISSUE TITLE
Unable to parse audio tags using 'fetchFromUrl'

### ISSUE THREAD

**Issue by Coders-Vision** [Borewit/music-metadata-browser#366]
I'm working on a music app using Vue framework, currently my app is on localhost server .I'm unable to parse the audio files which is .in .mp3 format located inside  'src/assets/songs' folder, the webpack seems to load the files without any issues but the 'fetchFromUrl' function throws 'Type Error: Failed to fetch' error in catch block. I've also checked the Network tab in chrome ,the status seems to be pending  for a while but fails eventually how can I rectify this?

![1](https://user-images.githubusercontent.com/73762430/97791941-ffa07300-1be8-11eb-9fc2-d4648ca11b9f.PNG)
![2](https://user-images.githubusercontent.com/73762430/97791944-0333fa00-1be9-11eb-932d-9a9ae8306b38.PNG)
![3](https://user-images.githubusercontent.com/73762430/97791945-04fdbd80-1be9-11eb-94de-b3f8c1f92cc3.PNG)
![4](https://user-images.githubusercontent.com/73762430/97791946-05965400-1be9-11eb-808c-564fbaab78ab.PNG)

**Comment by Borewit** [comment]
It looks like the error thrown because you browser is unable read the media files from the provided URL. You could try to click on URL of the media files, of all works fine, I that file should part play, but I bet it will not...

Embedding audio files in you source code is probably not a very good idea. Normally you would use some server side HTTP service which reads the file from you local file system.

**Comment by Coders-Vision** [comment]
Looks like my issue was nothing to do with the API.I tried isolating the problem by simply using the  'fetch() ' function by loading the file URL from the assets, but the fetch function was  throwing promise pending/unfulfilled not just for the .mp3 but for all audio files. I tried loading text based file like txt,pdf which loaded with no issues, looks like it was something to do with the Node environment. I deployed the project on another machine which works flawlessly.
