### ISSUE TITLE
Add `parsers` option in `parseFile` to minimize bundle size

### ISSUE THREAD

**Issue by chronoDave** [Borewit/music-metadata-browser#374]
**Feature Request**

![Webpack-bundle-analyzer output](https://i.imgur.com/qVmJL9z.png)

As seen in the screenshot, all parsers are included in the `music-metadata` bundle. I'm curious if it's possible to reduce the bundle size when using a selection of parsers (such as ID3v2 and ID3v1). This is useful when you know what type of files you're dealing with beforehand.

**Steps to reproduce**

```JS
// src/index.js
const { parseFile } = require('music-metadata');
```

```JS
// webpack.config.js
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');

module.exports = {
  plugins: [new BundleAnalyzerPlugin()],
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendors: {
          name: 'vendors',
          test: /[\\/]node_modules[\\/]/,
          chunks: 'all'
        }
      }
    }
  }
}
```

```
webpack --mode production
```

**Suggestion**

I'm not entirely sure how feasible this suggestion is, but it would be nice if something like this would be possible:

```JS
const { parseFile } = require('music-metadata');

parseFile(file, { parsers: ['id3v1', 'id3v2'] })
```

This way you keep the flexibility of automatically grabbing the correct parser for the file, but limit the amount of parsers it should check for (and hopefully decrease the overall bundle size by doing so).

**Comment by Borewit** [comment]
I assume you are talking about the browser version [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) if you talk about bundle size, because on Node.js these are insignificant numbers.

As you can see in you size analysis, the individual parsers are not that big. They share code is the bigger portion. As soon as I do that can of optimization users will complain parses are not included by the bundler or that it is to cumbersome. 

Alternatively you could use [jsmediatags](https://github.com/aadsm/jsmediatags) which is smaller parser, (~1/4) compared to this one, but you loose a bit of quality and a lot of functionality and support for many formats.

**Comment by chronoDave** [comment]
Ah, excuse me, I should have specified!

I am using the regular version (music-metadata) as I'm running it inside Electron. You raise a valid point regarding the absolute size, but the relative size of the "unused" code is fairly big if you consider the use case where an user is only using, for example, the ID3v2 parser.

Regarding the alternative, I'm very satisfied with your package (simply put, it works amazingly well) so I won't be switching anytime soon, but I do appreciate the suggestion.

In the end, this is just a simple "is this possible?" request. If it isn't possible / you do not feel it's worth pursuing, that's completely fine, of course.

**Comment by Borewit** [comment]
It is not feasible, and there are not many user who will only user it for one type of audio file.
