### ISSUE TITLE
'TypeError: this.parseReadableStream is not a function' on latest version 2.5.1

### ISSUE THREAD

**Issue by hvianna** [Borewit/music-metadata-browser#707]
Updated to version 2.5.1 and I'm getting this error: `TypeError: this.parseReadableStream is not a function`.

I'm actually using the `fetchFromUrl()` method in my code. If I revert to 2.5.0 it works as intended.

Thanks.

**Comment by Borewit** [comment]
It looks like this issue is context specific, I could not reproduce it. 
I cannot directly explain the issue.
A wild guess  is the `this` reference which does not made a lot of sense as it was not used with a class.

Any improvement in version [v2.5.2](https://github.com/Borewit/music-metadata-browser/releases/tag/v2.5.2)?

**Comment by hvianna** [comment]
@Borewit v2.5.2 works fine! Thank you!
